# Generated by Django 2.0 on 2019-10-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.TextField(default='', max_length=255, verbose_name='username')),
                ('first_name', models.TextField(default='', max_length=255, verbose_name='first_name')),
                ('last_name', models.TextField(default='', max_length=255, verbose_name='last_name')),
                ('password', models.TextField(default='', max_length=50, verbose_name='last_name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
