# Generated by Django 2.0 on 2019-11-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('fitness_group', models.CharField(max_length=70)),
                ('category_level', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=80)),
                ('specialization_type', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('program_duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('benefits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('week_day', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attendee_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('session_duraton', models.DecimalField(decimal_places=2, max_digits=5)),
                ('session_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50, null=True)),
                ('browser', models.CharField(max_length=40, null=True)),
                ('browser_version', models.CharField(max_length=50, null=True)),
                ('os', models.CharField(max_length=40, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('session_accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impression_count', models.IntegerField()),
                ('ip_address', models.CharField(max_length=30)),
                ('comments', models.TextField(null=True)),
                ('user_duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('session_id', models.ForeignKey(on_delete='', to='home.Session')),
            ],
        ),
    ]
