# Generated by Django 2.0 on 2019-11-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='user_id',
            field=models.ForeignKey(on_delete='', to='users.User'),
        ),
        migrations.AddField(
            model_name='session',
            name='fitness_id',
            field=models.ForeignKey(on_delete='', related_name='fitness_tpypes', to='home.Fitness'),
        ),
        migrations.AddField(
            model_name='session',
            name='instructor_id',
            field=models.ForeignKey(on_delete='', related_name='user', to='users.User'),
        ),
    ]
